name: SecureShop DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  ci-security:
    name: Tests et securite
    runs-on: ubuntu-latest

    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.2"
          cache: npm

      - name: Installation des dependances
        run: npm ci

      - name: Analyse ESLint
        run: npm run lint

      - name: Tests automatises
        run: npm run test:unit

      - name: Test build et rendu
        run: npm test

      - name: Audit npm
        run: npm audit --audit-level=critical

      - name: Recherche de secrets avec Gitleaks
        run: |
          docker run --rm \
            -v "$PWD:/repo" \
            zricethezav/gitleaks:latest \
            detect \
            --source=/repo \
            --config=/repo/.gitleaks.toml \
            --redact

      - name: Construction de l'image Docker
        run: docker build -t secureshop:ci .

      - name: Scan Trivy complet
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 0 \
            secureshop:ci

      - name: Blocage des vulnerabilites critiques
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            secureshop:ci

      - name: Connexion a GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preparation des tags Docker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag secureshop:ci "${IMAGE_NAME}:latest"
          docker tag secureshop:ci "${IMAGE_NAME}:${GITHUB_SHA}"

      - name: Publication dans GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:${GITHUB_SHA}"
